### ISSUE TITLE
PA Review: Wiki Pages

### ISSUE THREAD

**Issue by aycelacap** [JonJWong/JWong-Eats#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

**Comment by aycelacap** [comment]
Jonathan. The wiki home is looking good so far. Go ahead and add a placeholder for your live site. You can use the the actual site until we deploy on heroku!

**Comment by JonJWong** [comment]
I've done this now
