### ISSUE TITLE
PA Review: Database Schema

### ISSUE THREAD

**Issue by aycelacap** [JonJWong/JWong-Eats#3]
# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [ ] Correctly formatted
    - [x] schema is written in a table format
    - [ ] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by aycelacap** [comment]
Hi Jonathan. Great job on the DB schema. In all your tables, you have a type in between not null and index for the details on some of your columns. Additionally, your menu_items table should be camel_cased. 
https://apidock.com/rails/ActiveRecord/ModelSchema/ClassMethods/table_name

**Comment by JonJWong** [comment]
Thanks! the menu-items was a typo I've fixed that. Are you asking that I rearrange the details such that not null and indexed are last?
